#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

set -o vi

# Some Enviromnent Variables
export PS1='[\u@\h \W]\$ '
export EDITOR="/usr/bin/vim"
export PATH=/usr/local/texlive/2014/bin/i386-linux:$PATH


# Aliases
alias ls="ls -Nh --color=auto"
alias remake="make clean; make"
alias v="vim"
alias ll="ls -l"
alias lt="ls -lrt"


# Useful Functions
function shush()
{
  eval "$@ &> /dev/null" &
}


# Other Scripts to source


# Set up the pretty prompt!

