"
" Vim RC File
"

set number
set tabstop=2
set expandtab
set autoindent
set cindent
set shiftwidth=2
set noswapfile

set nohlsearch

set backup
set backupdir=~/.vim/backup
set directory=~/.vim/tmp

set wildmenu
set wildmode=list:longest,longest

set mouse=a
set syntax=enable
syntax on

set laststatus=2
set tabline=2


"
" Airline Configuration
"
let g:airline_theme='ubaryd'
let g:airline_detect_whitespace=0
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#lef_sep='>'
let g:airline#extensions#tabline#lef_alt_sep='>'
let g:airline#extensions#tabline#tab_nr_type=1
let g:airline#extensions#tabline#show_buffers=0
let g:airline#extensions#tabline#buffer_min_count=1


